global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'info_balancer'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'forum1'
    static_configs:
      - targets: ['84.201.188.179:5000']

  - job_name: 'srv1'
    static_configs:
      - targets: ['84.201.188.179:9100']

  - job_name: 'forum2'
    static_configs:
      - targets: ['51.250.51.252:5000']

  - job_name: 'srv2'
    static_configs:
      - targets: ['51.250.51.252:9100']

  - job_name: 'forum3'
    static_configs:
      - targets: ['51.250.126.245:5000']

  - job_name: 'srv3'
    static_configs:
      - targets: ['51.250.126.245:9100']
